version: "3"
name: vectorexample 
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
      # - ./postgres/0-vector-extension.sh:/docker-entrypoint-initdb.d/0-vector-extension.sh

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectorexample
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    ports:
      - "8000:8000"
      - "5432:5432"
    
    environment:
     - OPENAI_API_KEY=
     - POSTGRES_PASSWORD=postgres
    
