# Generated by Django 5.0 on 2024-01-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='answer',
            field=models.TextField(),
        ),
    ]
